### ISSUE TITLE
Can the follow button be displayed directly on the user's homepage for others to follow?

### ISSUE THREAD

**Issue by essesoul** [imorland/follow-users#11]
Can the follow button be displayed directly on the user's homepage for others to follow?

**Comment by imorland** [comment]
Hey @essesoul 

The following of a user can currently be accessed from another user's profile, like so:
![image](https://user-images.githubusercontent.com/16573496/169616124-20874a19-4f52-46a7-94b7-9a11ff315bc1.png)

Is this what you meant, or something different?

**Comment by essesoul** [comment]
![image](https://user-images.githubusercontent.com/58624474/169650649-f6949a91-12ee-45b8-af76-1978045e1416.png)
At present this function is very useful, but it is still a bit difficult for the user to find the button, it may be better if the button can be changed.
Also, hopefully the number of followers can be displayed next to the button.

**Comment by essesoul** [comment]
Also, how can I display these two content in the forum?
![image](https://user-images.githubusercontent.com/58624474/169657566-1d6a8752-fd3c-450b-a18b-67ba41b75e87.png)

**Comment by imorland** [comment]
> ![image](https://user-images.githubusercontent.com/58624474/169650649-f6949a91-12ee-45b8-af76-1978045e1416.png) At present, this function works well, but it is still a bit difficult for users to find the button. It may be better if the button position can be changed to the position of the box as shown in the figure. Also, hopefully the number of followers can be displayed next to the button.

I guess it would be fairly simple to offer a setting to determine if the `follow` button is displayed right there on the card, or in the menu... Leave that with me, I'll see what I can do for the next release :)

**Comment by imorland** [comment]
> Also, how can I display these two content in the forum? ![image](https://user-images.githubusercontent.com/58624474/169657566-1d6a8752-fd3c-450b-a18b-67ba41b75e87.png)

These are the latest versions of `fof/best-answer` and `fof/gamification`. You might also like https://discuss.flarum.org/d/30873-blomstra-usercard-stats, which also adds discussion and comment counts here too ;)

**Comment by imorland** [comment]
> Can the follow button be displayed directly on the user's homepage for others to follow?

Available in version `1.1.0`

**Comment by iamdarkle** [comment]
This is something I've been thinking about for a long time, so good that you've implemented it! 

I just have a suggestion @imorland, don't you think it would look better together with the Controls button? That way for the guests it would take its position and it would look pretty clean.

![Screenshot 2022-05-24 202347](https://user-images.githubusercontent.com/15818451/170106382-f259a3a3-c5e3-40dc-aa74-f0901244f053.png)
