### ISSUE TITLE
`addSubscriptionBadge()` is unused?

### ISSUE THREAD

**Issue by rob006** [imorland/follow-users#6]
https://github.com/imorland/follow-users/blob/ff2b9f350cdcdb74fed81bc9670b0d096956ec13/js/src/forum/addFollowBadge.js#L6

I hasn't been able to find any usage of this method and related translations in this repo.

**Comment by davwheat** [comment]
Its imported as `addFollowBadge`. Looks like the name stuck around from something else and I didn't change it. My bad.

https://github.com/imorland/follow-users/blob/ff2b9f350cdcdb74fed81bc9670b0d096956ec13/js/src/forum/index.js#L13

Translations are here:
https://github.com/imorland/follow-users/blob/ff2b9f350cdcdb74fed81bc9670b0d096956ec13/resources/locale/en.yml#L33-L36
