### ISSUE TITLE
TypeError: this.followed is not a function

### ISSUE THREAD

**Issue by iPurpl3x** [imorland/follow-users#7]
https://github.com/imorland/follow-users/commit/cf6c26d6cee7cb42b46801f3c63a7852f6559c37#r53984926

**Comment by davwheat** [comment]
You're totally right! That should be `this.user.followed()`.

Will update and patch release ASAP.

**Comment by davwheat** [comment]
@iPurpl3x Master branch should have a fix. If you could double check this solves the issue, that'd be great.

If not, I'll test it later this afternoon.

**Comment by davwheat** [comment]
Released [1.0.2](https://github.com/imorland/follow-users/releases/tag/1.0.2).
